version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://34.227.102.186:5000
      - USE_TAILWIND=false
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis-node-0
    environment:
      - NODE_ENV=development
      - PORT=5000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dataflowdb
      - REDIS_HOST=redis-node-0
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_password
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - app-network
      - redis-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dataflowdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis-node-0:
    image: bitnami/redis-cluster:latest
    ports:
      - "7000:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis-node-0-data:/bitnami
    networks:
      - redis-network
    restart: unless-stopped

  redis-node-1:
    image: bitnami/redis-cluster:latest
    ports:
      - "7001:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis-node-1-data:/bitnami
    networks:
      - redis-network
    restart: unless-stopped

  redis-node-2:
    image: bitnami/redis-cluster:latest
    ports:
      - "7002:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis-node-2-data:/bitnami
    networks:
      - redis-network
    restart: unless-stopped

  redis-node-3:
    image: bitnami/redis-cluster:latest
    ports:
      - "7003:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis-node-3-data:/bitnami
    networks:
      - redis-network
    restart: unless-stopped

  redis-node-4:
    image: bitnami/redis-cluster:latest
    ports:
      - "7004:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis-node-4-data:/bitnami
    networks:
      - redis-network
    restart: unless-stopped

  redis-node-5:
    image: bitnami/redis-cluster:latest
    ports:
      - "7005:6379"
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - redis-node-5-data:/bitnami
    networks:
      - redis-network
    restart: unless-stopped

  redis-cluster-init:
    image: bitnami/redis-cluster:latest
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    environment:
      - REDIS_PASSWORD=redis_password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_CLUSTER_SLEEP_BEFORE_DNS_LOOKUP=10
      - REDIS_CLUSTER_DNS_LOOKUP_RETRIES=30
      - REDIS_CLUSTER_DNS_LOOKUP_SLEEP=1
    networks:
      - redis-network
      
volumes:
  postgres-data:
  redis-node-0-data:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:

networks:
  app-network:
    driver: bridge
  redis-network:
    driver: bridge