version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=userdb
      - REDIS_NODES=redis-node-0:6379,redis-node-1:6379,redis-node-2:6379,redis-node-3:6379,redis-node-4:6379,redis-node-5:6379
      - REDIS_PASSWORD=password
      - PORT=5000

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=userdb
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis-node-0:
    image: bitnami/redis-cluster:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
      - REDIS_CLUSTER_REPLICAS=1
      - REDIS_CLUSTER_CREATOR=yes
    volumes:
      - redis_node_0_data:/bitnami/redis/data

  redis-node-1:
    image: bitnami/redis-cluster:latest
    ports:
      - "6380:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - redis_node_1_data:/bitnami/redis/data

  redis-node-2:
    image: bitnami/redis-cluster:latest
    ports:
      - "6381:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - redis_node_2_data:/bitnami/redis/data

  redis-node-3:
    image: bitnami/redis-cluster:latest
    ports:
      - "6382:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - redis_node_3_data:/bitnami/redis/data

  redis-node-4:
    image: bitnami/redis-cluster:latest
    ports:
      - "6383:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - redis_node_4_data:/bitnami/redis/data

  redis-node-5:
    image: bitnami/redis-cluster:latest
    ports:
      - "6384:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5
    volumes:
      - redis_node_5_data:/bitnami/redis/data

volumes:
  mysql_data:
  redis_node_0_data:
  redis_node_1_data:
  redis_node_2_data:
  redis_node_3_data:
  redis_node_4_data:
  redis_node_5_data: