version: '3'

services:
  # Frontend React Application
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - search-service
      - review-service
    environment:
      - REACT_APP_PRODUCT_API_URL=http://52.90.27.183:4000
      - REACT_APP_SEARCH_API_URL=http://52.90.27.183:5000
      - REACT_APP_REVIEW_API_URL=http://52.90.27.183:8080

  # Node.js Product Service
  product-service:
    build:
      context: ./services/product-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo

  # Python Search Service
  search-service:
    build:
      context: ./services/search-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo

  # Java Review Service
  review-service:
    build:
      context: ./services/review-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo

  # MongoDB Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: